# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8917-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter rova,$(TARGET_DEVICE)),)

endif
